### ISSUE TITLE
`postInitialize` is deprecated, please use `initialize`

### ISSUE THREAD

**Issue by sahanDissanayake** [rendrjs/rendr#374]
There is this error popping up on the terminal as the application is running

**Comment by roncli** [comment]
Assuming rendrjs/rendr-examples/00_simple, here are all of the changes I make to get to rendr 1.0.0 and be compatible with handlebars 2.0.0:

1) Update the app's dependencies:
* rendr to 1.0.0
* rendr-handlebars to 0.2.4
* grunt-contrib-handlebars to ~0.9.0 - This is needed because this is the earliest version of grunt-contrib-handlebars that supports handlebars 2.0.0 API.
* karma to ~0.12.8 - This is needed due to karma-mocha 0.1.10 requiring karma 0.12.8.  Resolves some weird circular dependency.

2) Edit app/app.js to use initialize instead of postInitialize, this makes the app compatible with rendr 1.0.0.

3) npm install to install the libraries.

Now you have to get rendr-handlebars to use the handlebars 2.0.0 API.

4) In node_modules/rendr-handlebars, update rendr-handlebars's dependencies:
* handlebars to 2.0.0

5) cd node_modules/rendr-handlebars

6) npm update handlebars

Now start the server, everything should work.

7) cd ../..

8) grunt server

9) Navigate to localhost:3030
