### ISSUE TITLE
Is this still used in production of airbnb or anywhere?

### ISSUE THREAD

**Issue by adyz** [rendrjs/rendr#508]
Is there any website using this library today in production?
Not sure, but from what I've seen the airbnb.com website has a full rerender when clicking on links.

**Comment by pjanuario** [comment]
@adyz as far as i know airbnb doesn't use rendr anymore, due to some internal needs and codebase. I was looking for something and about this, but I didn't find the link anymore, but as fare as I know was related with there rails codebase and product shipping lifecycle.

This issue contains some info about people using it in production.
https://github.com/rendrjs/rendr/issues/430

**Comment by adyz** [comment]
Ow, thanks for the link!
